/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.martinleopold.mode.clojure;

import java.util.ArrayList;
import processing.app.RunnerListener;
import processing.app.SketchException;
import processing.mode.java.runner.Runner;

/**
 *
 * @author mlg
 */
public class ClojureRunner extends Runner {
	public ClojureRunner(ClojureBuild build, RunnerListener listener) throws SketchException {
          super(build, listener);
      }
	
	/*
	 * protected VirtualMachine launchVirtualMachine(String[] vmParams, String[] classParams)
	 * the vm is launched with String[] vmParams and String[] classParmas
	 * vmParams contain -d -X -d -cp
	 * classParams is the last in the launch cmd line and contains the class (w/main method) to be launched
	 * 
	 * vmParams are generated by String[] getMachineParams()
	 * classParmas are generated by String[] getSketchParams()
	 * 
	 */
      

  
  /*
   * 
   * 
   */
    @Override
  protected String[] getSketchParams() {
    ArrayList<String> params = new ArrayList<String>();
    
    params.add("clojure.main");
    params.add(((ClojureBuild)build).getClojureFile());
    
    return (String[]) params.toArray(new String[0]);
  }
}
